### DISCUSSION TITLE
Adjust ContentEditable and Placeholder Left Padding if DraggableBlock Plugin is Enabled.

### DISCUSSION THREAD

**Discussion by 58bits** [AlessioGr/payload-plugin-lexical#37] [Feature Requests]
Consider adding editorConfig check and toggle to determine whether the DraggableBlock plugin is enabled and displayed, and if so, adjust the left padding of ContentEditable and Placeholder. For example for `ContentEditable` (and the same for Placeholder)..._ 

```js
/**
import * as React from 'react'

import { ContentEditable } from '@lexical/react/LexicalContentEditable'
import cx from 'classnames'

import type { EditorConfig } from '../types'

import './content-editable.scss'

export default function LexicalContentEditable ({
  className,
  editorConfig,
}: {
  className?: string
  editorConfig?: EditorConfig
}): JSX.Element {


  const classes = cx(className, 
    'ContentEditable__root',
    {'ContentEditable__with_draggable_blocks': editorConfig?.toggles?.draggableBlocks?.display}
  )

  return <ContentEditable className={classes} />
}
```

```css
.ContentEditable__root {
  border: 0;
  font-size: 15px;
  display: block;
  position: relative;
  tab-size: 1;
  outline: 0;
  padding: 8px 2px 40px;
}

.ContentEditable__with_draggable_blocks {
  padding: 8px 2px 40px 22px;
}

@media (max-width: 1025px) {
  .ContentEditable__root {
    padding-left: 2px;
    padding-right: 2px;
  }
}
```
